import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import { Footer } from "./components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import { Layout } from "./components/Layout/Layout";
import { Overlay } from "./components/ui/Overlay";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Overlay />
          <Header />
          {children}
          <Footer />
          <Toaster />
        </Layout>
      </body>
    </html>
  );
}
